// src/components/layout/Navbar.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { useWindowScroll } from '@vueuse/core';
import ThemeToggle from '../ui/ThemeToggle.vue';
import { NAV_LINKS } from '../../data/constants';
import { openCommandPalette } from '../../stores/commandPalette';

const { y } = useWindowScroll();
const isScrolled = ref(false);
const menuOpen = ref(false);

watch(y, (newY) => {
  isScrolled.value = newY > 50;
});

// Lock body scroll when mobile drawer is open
watch(menuOpen, (open) => {
  if (typeof document !== 'undefined') {
    document.body.style.overflow = open ? 'hidden' : 'unset';
  }
});

const closeMenu = () => {
  menuOpen.value = false;
};
</script>

<template>
  <nav
    :class="[
      'fixed top-0 left-0 w-full z-50 transition-all duration-300 border-b-4',
      isScrolled
        ? 'bg-white/90 dark:bg-black/90 backdrop-blur-md py-2 border-black dark:border-primary shadow-md'
        : 'bg-transparent py-4 border-transparent'
    ]"
  >
    <div class="max-w-6xl mx-auto px-4 flex justify-between md:justify-center items-center relative">
      <!-- Mobile Menu Button -->
      <button
        type="button"
        class="md:hidden text-gray-800 dark:text-white p-2 cursor-pointer"
        @click="menuOpen = !menuOpen"
        aria-label="Abrir menú de navegación"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter">
          <line x1="3" y1="12" x2="21" y2="12"></line>
          <line x1="3" y1="6" x2="21" y2="6"></line>
          <line x1="3" y1="18" x2="21" y2="18"></line>
        </svg>
      </button>

      <!-- Mobile Menu Overlay -->
      <div
        :class="[
          'fixed inset-0 bg-white dark:bg-black z-[100] flex flex-col items-center justify-center gap-8 transition-transform duration-300 md:hidden',
          menuOpen ? 'translate-x-0' : 'translate-x-full'
        ]"
      >
        <button
          type="button"
          class="absolute top-6 right-6 text-gray-800 dark:text-white p-2 cursor-pointer"
          @click="closeMenu"
          aria-label="Cerrar menú"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button>

        <ul class="flex flex-col gap-6 text-center">
          <li v-for="link in NAV_LINKS" :key="link.name">
            <a
              :href="link.href"
              @click="closeMenu"
              class="text-2xl font-pixel text-gray-800 dark:text-white hover:text-primary uppercase tracking-wider block"
            >
              {{ link.name }}
            </a>
          </li>
        </ul>

        <div class="flex items-center gap-4 mt-4">
          <button
            type="button"
            @click="() => { closeMenu(); openCommandPalette(); }"
            class="pixel-btn px-4 py-2 bg-primary/10 text-primary font-pixel text-lg flex items-center gap-2"
          >
            <span>Buscar (⌘K)</span>
          </button>
          <ThemeToggle />
        </div>
      </div>

      <!-- Desktop Menu -->
      <div class="flex items-center gap-6">
        <ul class="hidden md:flex gap-6 lg:gap-8 items-center">
          <li v-for="link in NAV_LINKS" :key="link.name">
            <a
              :href="link.href"
              class="text-lg lg:text-xl font-pixel text-gray-600 dark:text-gray-300 hover:text-primary dark:hover:text-secondary uppercase tracking-wider relative group"
            >
              {{ link.name }}
              <span class="absolute -bottom-1 left-0 w-0 h-1 bg-primary transition-all duration-300 group-hover:w-full" />
            </a>
          </li>
        </ul>

        <!-- Command Palette Trigger Button -->
        <button
          type="button"
          @click="openCommandPalette"
          class="hidden sm:flex items-center gap-2 px-3 py-1.5 border-2 border-dashed border-gray-400 dark:border-gray-600 hover:border-primary text-gray-600 dark:text-gray-300 font-pixel text-sm hover:text-primary transition-colors cursor-pointer"
          title="Buscar comandos o secciones (Cmd+K)"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
          <span>⌘K</span>
        </button>

        <ThemeToggle />
      </div>
    </div>
  </nav>
</template>

// Front-End/src/components/Navbar.jsx
import React, { useState, useEffect } from 'react';
import ThemeToggle from './ThemeToggle';

const Navbar = () => {
   const [scrolled, setScrolled] = useState(false);
   const [menuOpen, setMenuOpen] = useState(false);

   useEffect(() => {
      const handleScroll = () => {
         setScrolled(window.scrollY > 50);
      };

      window.addEventListener('scroll', handleScroll);
      return () => window.removeEventListener('scroll', handleScroll);
   }, []);

   // Lock body scroll when menu is open
   useEffect(() => {
      if (menuOpen) {
         document.body.style.overflow = 'hidden';
      } else {
         document.body.style.overflow = 'unset';
      }
      return () => {
         document.body.style.overflow = 'unset';
      };
   }, [menuOpen]);

   const links = [
      { name: 'Inicio', href: '#hero' },
      { name: 'Sobre Mí', href: '#about' },
      { name: 'Proyectos', href: '#projects' },
      { name: 'Certificados', href: '#certifications' },
      { name: 'Contacto', href: '#contact' },
   ];

   return (
      <nav
         className={`fixed top-0 left-0 w-full z-50 transition-all duration-300 border-b-4 ${scrolled
            ? 'bg-white/90 dark:bg-black/90 backdrop-blur-md py-2 border-black dark:border-primary'
            : 'bg-transparent py-4 border-transparent'
            } `}
      >
         <div className="max-w-6xl mx-auto px-4 flex justify-between md:justify-center items-center relative">
            {/* Mobile Menu Button - Visible on Mobile */}
            <button
               className="md:hidden text-gray-800 dark:text-white p-2"
               onClick={() => setMenuOpen(!menuOpen)}
            >
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="square" strokeLinejoin="miter">
                  <line x1="3" y1="12" x2="21" y2="12"></line>
                  <line x1="3" y1="6" x2="21" y2="6"></line>
                  <line x1="3" y1="18" x2="21" y2="18"></line>
               </svg>
            </button>

            {/* Mobile Menu Overlay */}
            <div className={`
               fixed inset-0 bg-white dark:bg-black z-[100] flex flex-col items-center justify-center gap-8 transition-transform duration-300 md:hidden
               ${menuOpen ? 'translate-x-0' : 'translate-x-full'}
            `}>
               <button
                  className="absolute top-6 right-6 text-gray-800 dark:text-white p-2"
                  onClick={() => setMenuOpen(false)}
               >
                  <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="square" strokeLinejoin="miter">
                     <line x1="18" y1="6" x2="6" y2="18"></line>
                     <line x1="6" y1="6" x2="18" y2="18"></line>
                  </svg>
               </button>
               <ul className="flex flex-col gap-8 text-center">
                  {links.map((link) => (
                     <li key={link.name}>
                        <a
                           href={link.href}
                           onClick={() => setMenuOpen(false)}
                           className="text-3xl font-pixel text-gray-800 dark:text-white hover:text-primary uppercase tracking-wider block"
                        >
                           {link.name}
                        </a>
                     </li>
                  ))}
               </ul>
            </div>

            {/* Desktop Menu */}
            <div className="flex items-center gap-8">
               <ul className="hidden md:flex gap-8">
                  {links.map((link) => (
                     <li key={link.name}>
                        <a
                           href={link.href}
                           className="text-xl font-pixel text-gray-600 dark:text-gray-300 hover:text-primary dark:hover:text-secondary uppercase tracking-wider relative group"
                        >
                           {link.name}
                           <span className="absolute -bottom-1 left-0 w-0 h-1 bg-primary transition-all duration-300 group-hover:w-full" />
                        </a>
                     </li>
                  ))}
               </ul>
               <ThemeToggle />
            </div>
         </div>
      </nav>
   );
};

export default Navbar;
